/* WARNING: must be kept in sync with kernel/syscall.h */

#define SYS_exit 0
#define SYS_read 1
#define SYS_write 2
#define SYS_open 3
#define SYS_close 4
#define SYS_unlink 5
#define SYS_seek 6
#define SYS_clone 7
#define SYS_waitpid 8
#define SYS_execve 9
#define SYS_vmop 10
#define SYS_dup 11
#define SYS_rename 12
#define SYS_stat 13
#define SYS_chdir 14
#define SYS_fstat 15
#define SYS_fchdir 16
#define SYS_fcntl 17
#define SYS_link 18
#define SYS_utime 19
#define SYS_clock_settime 20
#define SYS_clock_gettime 21
#define SYS_clock_getres 22
#define SYS_readlink 23
#define SYS_lstat 24
#define SYS_getcwd 25
#define SYS_sigaction 26
#define SYS_sigprocmask 27
#define SYS_sigsuspend 28
#define SYS_kill 29
#define SYS_sigreturn 30
#define SYS_ioctl 31
#define SYS_getpgrp 32
#define SYS_setpgid 33
#define SYS_setsid 34
#define SYS_dup2 35
#define SYS_mount 36
#define SYS_unmount 37
#define SYS_statfs 38
#define SYS_fstatfs 39
#define SYS_nanosleep 40
#define SYS_getsid 41
#define SYS_getuid 42
#define SYS_geteuid 43
#define SYS_getgid 44
#define SYS_getegid 45
#define SYS_getpid 46
#define SYS_getppid 47
#define SYS_symlink 48
#define SYS_reboot 49
